"""Regenerate ``link_screen_sites.py`` from the gate's own discovery.

Run from the repository root::

    python3 test/gen_link_screen_sites.py > test/link_screen_sites.py

The baseline is generated rather than hand-written so it cannot drift from the
condition the gate actually evaluates: both come from ``discovered_sites``.
Adding a site by hand would let the list claim a shape the gate never checked.

The count is written to stderr as a sentinel, so a run that produces no output is
distinguishable from a run that found nothing.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path[:0] = [str(Path(__file__).resolve().parent), "src"]

from test_link_screen_hold_pin import discovered_sites  # noqa: E402

HEADER = '''"""The declared baseline of screen-then-resolve-by-name sites.

A site reaches this list one of two ways, and the distinction is the whole point.

Either it HOLDS its chain across the screen and the use, so the object the screen
inspected is the object the use reaches. Those sites are also named in
``HELD_SITES`` in the gate module, which asserts the shape structurally.

Or a hold is not the answer for it, because it refuses every link and never
traverses one. Tightening such a site further costs an ordinary layout -- a
junction or symlink on the path to a config directory, which a dotfile manager
produces on purpose -- and buys no privilege back.

The list is the baseline the condition's output is compared against. It is NEVER
the search key: the gate enumerates from source by the condition, so a new site
is found because it matches the shape, not because it resembles one of these.

Generated by ``gen_link_screen_sites.py``; regenerate rather than edit by hand.
"""

'''


def main() -> int:
    sites = sorted(discovered_sites())
    out = [HEADER, "DECLARED_SITES = frozenset(\n", "    {\n"]
    out += [f'        ("{module}", "{func}"),\n' for module, func in sites]
    out += ["    }\n", ")\n"]
    sys.stdout.write("".join(out))
    print(f"SENTINEL count={len(sites)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
